#!/bin/bash
# Claude Code ROI Report Generator
# Fetches metrics from Prometheus and generates a report

set -e

PROMETHEUS_URL="${PROMETHEUS_URL:-http://localhost:9090}"
RANGE="${RANGE:-7d}"

echo "Fetching Claude Code metrics from Prometheus..." >&2

# Helper to fetch metric value
fetch_metric() {
  local query="$1"
  local result
  result=$(curl -s "${PROMETHEUS_URL}/api/v1/query?query=${query}" | jq -r '.data.result[0].value[1] // "0"')
  # Handle null/empty
  if [ -z "$result" ] || [ "$result" = "null" ]; then
    echo "0"
  else
    echo "$result"
  fi
}

# Fetch metrics
TOTAL_COST=$(fetch_metric "sum(increase(claude_code_cost_usage_USD_total[${RANGE}]))")
INPUT_TOKENS=$(fetch_metric "sum(increase(claude_code_token_usage_tokens_total{type=\"input\"}[${RANGE}]))")
OUTPUT_TOKENS=$(fetch_metric "sum(increase(claude_code_token_usage_tokens_total{type=\"output\"}[${RANGE}]))")
CACHE_READ=$(fetch_metric "sum(increase(claude_code_token_usage_tokens_total{type=\"cacheRead\"}[${RANGE}]))")
CACHE_CREATED=$(fetch_metric "sum(increase(claude_code_token_usage_tokens_total{type=\"cacheCreation\"}[${RANGE}]))")
SESSIONS=$(fetch_metric "count(count%20by%20(session_id)(claude_code_cost_usage_USD_total))")
ACTIVE_TIME=$(fetch_metric "sum(increase(claude_code_active_time_seconds_total[${RANGE}]))")
LINES_ADDED=$(fetch_metric "sum(increase(claude_code_lines_of_code_count_total{type=\"added\"}[${RANGE}]))")
LINES_REMOVED=$(fetch_metric "sum(increase(claude_code_lines_of_code_count_total{type=\"removed\"}[${RANGE}]))")
PRS=$(fetch_metric "sum(increase(claude_code_pull_request_count_total[${RANGE}]))")
COMMITS=$(fetch_metric "sum(increase(claude_code_commit_count_total[${RANGE}]))")
EDITS_ACCEPTED=$(fetch_metric "sum(increase(claude_code_code_edit_tool_decision_total{decision=\"accept\"}[${RANGE}]))")
EDITS_REJECTED=$(fetch_metric "sum(increase(claude_code_code_edit_tool_decision_total{decision=\"reject\"}[${RANGE}]))")

# Provider breakdown
BEDROCK_COST=$(fetch_metric "sum(increase(claude_code_cost_usage_USD_total{provider=\"bedrock\"}[${RANGE}]))")
MAX_COST=$(fetch_metric "sum(increase(claude_code_cost_usage_USD_total{provider=\"anthropic-max\"}[${RANGE}]))")

# Calculate derived metrics using awk (more portable than bc)
COST_PER_PR=$(awk -v cost="$TOTAL_COST" -v prs="$PRS" 'BEGIN { if (prs > 0) printf "%.2f", cost/prs; else print "N/A" }')
ACCEPT_RATE=$(awk -v accepted="$EDITS_ACCEPTED" -v rejected="$EDITS_REJECTED" 'BEGIN { total=accepted+rejected; if (total > 0) printf "%.1f", 100*accepted/total; else print "N/A" }')
CACHE_RATIO=$(awk -v read="$CACHE_READ" -v created="$CACHE_CREATED" 'BEGIN { if (created > 0) printf "%.1f", read/created; else print "N/A" }')
ACTIVE_HOURS=$(awk -v secs="$ACTIVE_TIME" 'BEGIN { printf "%.1f", secs/3600 }')
NET_LINES=$(awk -v added="$LINES_ADDED" -v removed="$LINES_REMOVED" 'BEGIN { printf "%.0f", added-removed }')

# Round token counts for display
INPUT_TOKENS=$(printf "%.0f" "$INPUT_TOKENS")
OUTPUT_TOKENS=$(printf "%.0f" "$OUTPUT_TOKENS")
CACHE_READ=$(printf "%.0f" "$CACHE_READ")
CACHE_CREATED=$(printf "%.0f" "$CACHE_CREATED")
LINES_ADDED=$(printf "%.0f" "$LINES_ADDED")
LINES_REMOVED=$(printf "%.0f" "$LINES_REMOVED")
PRS=$(printf "%.0f" "$PRS")
COMMITS=$(printf "%.0f" "$COMMITS")
SESSIONS=$(printf "%.0f" "$SESSIONS")
EDITS_ACCEPTED=$(printf "%.0f" "$EDITS_ACCEPTED")
EDITS_REJECTED=$(printf "%.0f" "$EDITS_REJECTED")

cat << EOF
# Claude Code ROI Report
**Period:** Last ${RANGE}
**Generated:** $(date)

## Summary

| Metric | Value |
|--------|-------|
| Total Cost | \$${TOTAL_COST} |
| Sessions | ${SESSIONS} |
| Active Time | ${ACTIVE_HOURS} hours |
| PRs Created | ${PRS} |
| Commits | ${COMMITS} |
| Cost/PR | \$${COST_PER_PR} |

## Token Usage

| Type | Count |
|------|-------|
| Input | ${INPUT_TOKENS} |
| Output | ${OUTPUT_TOKENS} |
| Cache Read | ${CACHE_READ} |
| Cache Created | ${CACHE_CREATED} |
| **Cache Ratio** | ${CACHE_RATIO}:1 |

## Code Changes

| Metric | Value |
|--------|-------|
| Lines Added | ${LINES_ADDED} |
| Lines Removed | ${LINES_REMOVED} |
| Net Change | ${NET_LINES} |

## Edit Acceptance

| Metric | Value |
|--------|-------|
| Accepted | ${EDITS_ACCEPTED} |
| Rejected | ${EDITS_REJECTED} |
| **Accept Rate** | ${ACCEPT_RATE}% |

## Provider Breakdown

| Provider | Cost |
|----------|------|
| Bedrock | \$${BEDROCK_COST} |
| Anthropic Max | \$${MAX_COST} |

---
*Generated by claude-metrics*
EOF
